baseURL = "https://fiverr-soundtown.netlify.app"
languageCode = "id-ID"
defaultContentLanguage = "id"
title = "SoundTown"
summaryLength = 10
RelativeURLs = false
CanonifyURLs = true
enableRobotsTXT = true
enableEmoji = true
paginate = 8
enableGitInfo = true
pygmentsCodefences = true 
pygmentsUseClasses = true

[params]
  author = "John Doe"
  site_name = "SoundTown"
  description = "SoundTown is an online music collaboration platform, focused on iterating on small ideas into big ideas. The main functionality at the moment is communication across groups/teams of people, uploading audio files and commenting on them."
  locale = "en-US"
  type = "website"

  primary_color = "#30B561" # Green Color

  landing_title = "Online Music Collaboration Platform"
  landing_description = "Lorem ispum dolor si amet jue viole grace"
  background_image = "/assets/images/bg.webp"

  learn_more_url = "#"
  try_now_url = "#"

  app_image_on_desktop = "/assets/images/app.webp"
  app_image_on_mobile = "/assets/images/app-mobile.webp"

  about = "SoundTown is an online music collaboration platform, focused on iterating on small ideas into big ideas. The main functionality at the moment is communication across groups/teams of people, uploading audio files and commenting on them."

  testimonials = [
    # [
      # 'Photo Url',
      # 'Name',
      # 'Testimonial'
    # ],
    [
      '/assets/images/m1.webp',
      'Abanz Levana',
      'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Diam dictum magna sociis arcu etiam cursus. Eget molestie donec et molestie ut a maecenas. Purus pharetra dictumst purus consequat sed orci facilisi.'
    ],
    [
      '/assets/images/m2.webp',
      'John Doe',
      'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Diam dictum magna sociis arcu etiam cursus.'
    ],
    [
      '/assets/images/m3.webp',
      'Xie Tzuyu',
      'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Diam dictum magna sociis arcu etiam cursus.'
    ],
    [
      '/assets/images/m3.webp',
      'Xie Tzuyu',
      'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Diam dictum magna sociis arcu etiam cursus.'
    ]
  ]

  contact_us_url = "#"
  privacy_url = "#"
  terms_url = "#"
  help_url = "#"

